# Generated by Django 5.2.8 on 2025-12-12 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Beta & OT', 'Beta & OT'), ('Daily Salary', 'Daily Salary'), ('Electricity', 'Electricity'), ('ESI & PF', 'ESI & PF'), ('Petrol & Diesel', 'Petrol & Diesel'), ('Phone Bill', 'Phone Bill'), ('Pooja', 'Pooja'), ('Donation', 'Donation'), ('Rental', 'Rental'), ('Repair & Maintenance', 'Repair & Maintenance'), ('Sweet', 'Sweet'), ('Travel Expenses', 'Travel Expenses'), ('Vessels', 'Vessels'), ('Wages', 'Wages'), ('Washing wages', 'Washing wages'), ('Water', 'Water'), ('New Joinee Advance', 'New Joinee Advance'), ('Interest and Bank Loan', 'Interest and Bank Loan')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'pcs'), ('kg', 'kg'), ('liters', 'liters'), ('person', 'person')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Credit', 'Credit')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
