# Generated by Django 6.0 on 2025-12-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
