# Generated by Django 5.2.8 on 2025-12-16 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Swiggy', 'Swiggy'), ('Zomato', 'Zomato')], max_length=50)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending')], default='Received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('vendor', models.CharField(choices=[('Ram', 'Ram'), ('Veera', 'Veera'), ('Local Purchase', 'Local Purchase')], max_length=100)),
                ('category', models.CharField(choices=[('Beeda', 'Beeda'), ('Coconut', 'Coconut'), ('Milk', 'Milk'), ('Vegetables', 'Vegetables'), ('Others', 'Others')], max_length=100)),
                ('bill_no', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('liters', 'liters'), ('pcs', 'pcs')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_applicable', models.BooleanField(default=True, verbose_name='GST Applicable')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Credit', 'Credit')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
