# Generated by Django 6.0.1 on 2026-01-18 09:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Swiggy', 'Swiggy'), ('Zomato', 'Zomato')], max_length=50)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending')], default='Received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_state', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('spr_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_split_type', models.CharField(choices=[('full_cash', '100% Cash'), ('full_bank', '100% Bank Transfer'), ('split', 'Split Payment')], default='full_cash', max_length=20)),
                ('bank_transfer_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage for bank transfer (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('cash_percentage', models.DecimalField(decimal_places=2, default=100, help_text='Percentage for cash payment (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('bank_transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('salary_date', models.DateField()),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('expenses_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payroll',
                'ordering': ['-year', '-month', 'employee_name'],
                'unique_together': {('employee_name', 'month', 'year', 'record_state')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_state', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Beta & OT', 'Beta & OT'), ('Daily Salary', 'Daily Salary'), ('Electricity', 'Electricity'), ('ESI & PF', 'ESI & PF'), ('Petrol & Diesel', 'Petrol & Diesel'), ('Phone Bill', 'Phone Bill'), ('Pooja', 'Pooja'), ('Donation', 'Donation'), ('Rental', 'Rental'), ('Repair & Maintenance', 'Repair & Maintenance'), ('Sweet', 'Sweet'), ('Travel Expenses', 'Travel Expenses'), ('Vessels', 'Vessels'), ('Wages', 'Wages'), ('Washing wages', 'Washing wages'), ('Water', 'Water'), ('New Joinee Advance', 'New Joinee Advance'), ('Interest and Bank Loan', 'Interest and Bank Loan'), ('Salary', 'Salary')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'pcs'), ('kg', 'kg'), ('liters', 'liters'), ('person', 'person')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Credit', 'Credit'), ('Salary', 'Salary')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='fine.payroll')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('vendor', models.CharField(max_length=100)),
                ('bill_no', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Net Banking', 'Net Banking')], default='Cash', max_length=50)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Due', 'Due')], default='Paid', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fine.cat')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_state', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Range')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days_in_period', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('present_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('half_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('absent_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('full_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='fine.payroll')),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'db_table': 'attendance_summary',
                'ordering': ['-start_date', 'employee_name'],
                'indexes': [models.Index(fields=['employee_name', 'start_date', 'end_date'], name='attendance__employe_18290b_idx'), models.Index(fields=['start_date', 'end_date'], name='attendance__start_d_d696e2_idx'), models.Index(fields=['employee_name'], name='attendance__employe_11e8c1_idx'), models.Index(fields=['period_type'], name='attendance__period__433871_idx')],
                'unique_together': {('employee_name', 'period_type', 'start_date', 'end_date', 'record_state')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_state', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('absent', 'Absent')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='fine.payroll')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', 'employee_name'],
                'unique_together': {('payroll', 'date', 'record_state')},
            },
        ),
    ]
