# Generated by Django 6.0.1 on 2026-01-18 10:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='worked_days',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Automatically calculated from attendance', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
