# Generated by Django 6.0.1 on 2026-01-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0002_payroll_worked_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='worked_days',
        ),
    ]
