# Generated by Django 6.0.1 on 2026-01-18 12:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0005_remove_payroll_worked_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='worked_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Worked days calculated from attendance records', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('31'))]),
        ),
    ]
