# Generated by Django 6.0 on 2026-01-20 14:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0006_payroll_worked_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='worked_days',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Number of days worked (calculated from attendance)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
