# Generated by Django 6.0 on 2026-01-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0007_alter_payroll_worked_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pcs'), ('kg', 'kg'), ('liters', 'liters'), ('person', 'person')], default='pcs', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
